### PR TITLE
Add gameplay

### PR DESCRIPTION
**Pull request by z4ab**
Added the base gameplay.
Computers don't always win.
The `difficulty` variable is a float which determines the chance that the computer will win.
Using the random library, if difficulty = a random number between 0 and 1 the computer wins and picks the right choice.
Otherwise, it will remove the player's choice and choose a random wrong choice for it to make more sense.

and btw I'm first lol I will happily take my W

Leave comments for fixes or optimizations. :)

### CODE REVIEW

**Comment by z4ab** [comment]
Oh yeah i noticed that the `list` variable overrides a built-in python type. I changed it to `ls` instead

**Comment by z4ab** [comment]
oopsie my search and replace changed README.md

**Comment by Dodopo2324** [comment]
Hey really nice job on the code. You are missing the parts where spock and lizard are included. I used your gameplay part of the code in mine, I gave you credits too, let me know if you are ok with that. If you want, the code is in my pfp. Feel free to look at it and change whatever you want.

**Comment by z4ab** [comment]
could you merge pls :) @Dodopo2324 @XavierCodingClub  this is my first official pr

**Comment by Dodopo2324** [comment]
Im sorry idk how to merge. @z4ab

**Pull request closed without merging**
